name: Manual Release

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version number for the release'
        required: true
        type: string

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Get repository name
      id: repo-name
      run: echo "REPO_NAME=$(basename $GITHUB_REPOSITORY)" >> $GITHUB_ENV

    - name: Create mcpack file
      run: |
        VERSION=${{ github.event.inputs.version }}
        REPO_NAME=${{ env.REPO_NAME }}
        ZIP_NAME="${REPO_NAME}-${VERSION}.mcpack"
        zip -r "${ZIP_NAME}" . -x "*.git*"
      env:
        VERSION: ${{ github.event.inputs.version }}
        REPO_NAME: ${{ env.REPO_NAME }}

    - name: Upload mcpack file
      uses: actions/upload-artifact@v3
      with:
        name: project-mcpack
        path: "${REPO_NAME}-${VERSION}.mcpack"

    - name: Create GitHub Release
      id: create_release
      uses: actions/create-release@v1
      with:
        tag_name: ${{ github.event.inputs.version }}
        release_name: Release ${{ github.event.inputs.version }}
        draft: false
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Upload release assets
      uses: actions/upload-release-asset@v1
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: "${REPO_NAME}-${VERSION}.mcpack"
        asset_name: "${REPO_NAME}-${VERSION}.mcpack"
        asset_content_type: application/zip
