name: Manual Release

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version number for the release'
        required: true
        type: string

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Get repository name and set environment variables
      id: repo-name
      run: |
        REPO_NAME=$(basename $GITHUB_REPOSITORY)
        echo "REPO_NAME=${REPO_NAME}" >> $GITHUB_ENV
        echo "VERSION=${{ github.event.inputs.version }}" >> $GITHUB_ENV
        echo "FILE_NAME=${REPO_NAME}-${{ github.event.inputs.version }}.mcpack" >> $GITHUB_ENV

    - name: Create mcpack file
      run: zip -r "${FILE_NAME}" . -x "*.git*"
      env:
        FILE_NAME: ${{ env.FILE_NAME }}

    - name: Upload Release
      uses: ncipollo/release-action@v1
      with:
        allowUpdates: true
        artifactErrorsFailBuild: true
        artifacts: '${{ env.FILE_NAME }}'
        tag: '${{ env.VERSION }}'
        token: ${{ secrets.GITHUB_TOKEN }}
